spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market?useUnicode=true&characterEncoding=utf-8
  messages:
    basename: i18n.login
#  main:
#    allow-circular-references: true

  #整合mybatis

mybatis:
  type-aliases-package: com.mydemo.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

