CREATE TABLE USER (
    id BIGINT(20) PRIMARY KEY NOT NULL COMMENT '主键',
    NAME VARCHAR(30) DEFAULT NULL COMMENT '姓名',
    PASSWORD INT(11) DEFAULT NULL COMMENT '密码',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
        update_time DATETIME DEFAULT NULL COMMENT '修改时间'
)  ENGINE=INNODB CHARSET=UTF8;