# yaml用key-value形式，对空格的要求严格
#可以存对象
#name: wjl

#对象
#student:
# name: wjl
# age: 3

#行内写法
#student: {name: wjl,age: 3}


#数组
#pets:
#  - cat
#  - dog
#  - pig

#pets: [cat,dog,pig]

person:
  name: wjl
  age: 5
  happy: false
  brith: 2022-02-28
  map: {k1: v1,k2: v2}
  list:
    - code
    - music
    - girl
  dog:
    name: 小乖
    age: 2

